### PR TITLE
Do not enforce proxy agent.

### PR DESCRIPTION
**Pull request by Patafix**

### CODE REVIEW

**Comment by brianleroux** [comment]
Hi 👋 ---can you provide some detail as to why you'd like this change?

**Comment by Patafix** [comment]
Hello sorry i was in a rush. I write a slack bot under corporate proxy.  This library dosent work with proxy beacause you force agents option to false.
With this code you cannot set http.globalAgent to allow set a proxy agent globally.

**Comment by Patafix** [comment]
https://nodejs.org/api/http.html#http_http_globalagent

**Comment by brianleroux** [comment]
np! will merge / wanted to check! 🙏

**Comment by brianleroux** [comment]
(published on npm at `v5.1`)

**Pull request merged**
