### PR TITLE
Don't wait for Node 8 - Promises now!

### PR DESCRIPTION
**Pull request by BigAB**
As an alternative to #4 I propose you just add this feature:

If no `callback` is supplied, return a promise, otherwise behave exactly as before.

This will work now, without waiting for node to be supported on lambda and will continue to work with async functions on node 8.

I tried to match the code style, I could of course change anything you don't like.

### CODE REVIEW

**Comment by brianleroux** [comment]
I really like this PR! Sorry I haven't gotten around to this --- I think we can merge but want to get #7 merged in first!

**Comment by BigAB** [comment]
Rebased onto master

**Comment by BigAB** [comment]
Added docs to Readme

**Comment by brianleroux** [comment]
thx a lot @BigAB / looks great! publishing in `5.3` 💜

**Pull request merged**
